---
apiVersion: v1
kind: Secret
metadata:
  name: evanshortiss-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-vegas/evanshortiss-frontend-gitops
